stages:
  - test
  - publish

test:
  stage: test
  image: node:13-alpine
  before_script:
    - yarn install
    - cd server && yarn install && cd ..
    - cd website && yarn install && cd ..
  script:
    - yarn cover
  cache:
    paths:
      - ./website/node_modules
      - ./server/node_modules
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

pages:
  stage: publish
  image: node:lts-alpine
  before_script:
    - cd website
    - yarn install
  script:
    - yarn build
    - mv dist ../public
  cache:
    paths:
      - ./website/node_modules
  artifacts:
    paths:
      - public
  only:
    - master
  when: manual

