name: CI

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13
      uses: actions/setup-node@v1
      with:
        node-version: 13
    - name: Prepare .env
      run: cp .ci-helpers/test-sample.env .env
    - name: Build containers
      run: docker-compose -f docker-compose-actions.yml up -d
    - name: Wait for containers
      run: node .ci-helpers/test-wait-for-server.js
    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules
    - name: Cache server/node_modules
      uses: actions/cache@v1
      with:
        path: server/node_modules
        key: ${{ runner.os }}-server-node_modules
    - name: Test
      run: yarn cover
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Kill containers
      run: docker-compose -f docker-compose-actions.yml down
