name: CI

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Prepare .env
      run: cp .ci-helpers/test-sample.env .env
    - name: Build containers
      run: docker-compose up -d --build --abort-on-container-exit
    - name: Wait for containers
      run: node .ci-helpers/test-wait-for-server.js
    - name: Test
      run: yarn cover
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Kill containers
      run: docker-compose down
